name: minesweepergo
description: Minesweeper game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  provider: ^6.0.3
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.2.1
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/appicon.png
    - assets/appiconrb.png

flutter_native_splash:
  color: "#000000"
  image: assets/appiconrb.png
  color_dark: "#000000"
  image_dark: assets/appiconrb.png

  android_12:
    image: assets/appiconrb.png
    icon_background_color: "#000000"
    image_dark: assets/appiconrb.png
    icon_background_color_dark: "#000000"

  web: false

flutter_icons:
  android: true
  image_path: "assets/appicon.png"